server:
  port: 8081
  servlet:
    context-path: /dabolo
spring:
  datasource:
    url: jdbc:mysql://192.168.0.109:3306/dabolo_design?characterEncoding=UTF-8
    username: root
    password: Passw00d
    driver-class-name: com.mysql.jdbc.Driver
logging:
  config: classpath:logback-boot.xml