upload:
  path: d:/dabolofiles/
  maxsize: 5MB
  requestsize: 10MB
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${upload.path}
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.smartions.model
wechat:
  appid: 
  secret: 
  message: 
    templeate-id: cg4ZoEJPM4eYw1aBIW83IAzL41q6uA2NEJpEJHLLI2I
    data: 测试内容
  
token: 
  secret: 123456
  timeout: 1800
activity: 
  distance: 2000
  notify: 3600

  
 