upload:
  path: D:/dabolofiles/
  maxsize: 5MB
  requestsize: 10MB
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${upload.path}
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.smartions.model
wechat:
  appid: 
  secret: 
token: 
  secret: 123456
  timeout: 1800

  
 