spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.smartions.model
wechat:
  appid: 
  secret: 
token: 
  secret: 123456
  timeout: 1800
  
 